### ISSUE TITLE
private helyet protected láthatóság

### ISSUE THREAD

**Issue by djozsef** [refaktormagazin/blog#4]
Jelenleg konzekvensen `private` láthatóságú tagváltozókat használunk getter/setter metódusokkal.
Ne használjunk inkább `protected`-et? Így később extend-elés során közvetlenül hozzáférhetők lennének.

**Comment by janoszen** [comment]
Ha protected, akkor a változó onnantól kezdve részét képezi az osztály API-jának. Azt hiszem, célszerűbb private-é tenni, hiszen így nem lehet módosítani az ezzel kapcsolatos üzleti logikán. (Open-Closed Principle.)

**Comment by djozsef** [comment]
Jogos, egyetértek. Open-Closed Principle FTW!
